services:
  token-exchange-service-test:
    profiles:
      - test
    build:
      context: ./token-exchange-service
    environment:
      SPRING_PROFILES_ACTIVE: test
    ports:
      - "8081:8081"
  token-exchange-service-prod:
    profiles:
      - prod
    build:
      context: ./token-exchange-service
    environment:
      SPRING_PROFILES_ACTIVE: prod
    ports:
      - "8081:8081"
