server:
  port: 8081

spring:
  application:
    name: token-generator-service
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true

auth:
  cache:
    max-size: 1000
    eorchestrator-ttl-seconds: 1800
    enm-ttl-seconds: 1800
