apiVersion: v1
kind: Service
metadata:
  name: token-generator-service
  namespace: apigw-token-service
  labels:
    app.kubernetes.io/name: token-generator-service
    app.kubernetes.io/component: api
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: token-generator-service
  ports:
    - name: http
      port: 8081
      targetPort: http
      protocol: TCP
